# Generated by Django 5.1.3 on 2024-11-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productimage',
            name='uniques_main_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='rate',
            new_name='rating',
        ),
        migrations.AddConstraint(
            model_name='productimage',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main_image', True)), fields=('product', 'is_main_image'), name='unique_main_image'),
        ),
    ]
